---

- name: Find Latest SourcePython build
  shell: "curl --silent http://downloads.sourcepython.com/ | grep -iPo '(?<=href=\").*source-python-tf2.*.zip' | uniq"
  register: sp
  run_once: true

- set_fact: 
    sourcepython_archive={{ sp.stdout }}

- name: Install SourcePython
  unarchive:
    src: "http://downloads.sourcepython.com/{{ sourcepython_archive }}"
    dest: "{{ srcds_root_dir }}/tf2/tf/"
    copy: no
    owner: "{{ srcds_user }}"
    group: "{{ srcds_user }}"

- name: Install Python3.6 pip
  apt:
    name: python3-pip
    state: present