---
- hosts: localhost
  become: true
  connection: local
  gather_facts: no

  vars:
    srcds_root_dir: /usr/games/steam/
    srcds_user: steam

  roles:
    - role: utils
    - role: security
    - role: monitoring
    - role: srcds

  tasks:
    - name: Create custom map folder
      file:
        path: "{{ srcds_root_dir }}/tf2/tf/custom/mapdl/maps/"
        state: directory
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"

    - name: Download custom maps
      get_url:
        url: "http://maps.tf2.games/maps/{{ item }}.bsp"
        dest: "{{ srcds_root_dir }}/tf2/tf/custom/mapdl/maps/{{ item }}.bsp"
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
        mode: 0444
      ignore_errors: yes
      with_items:
      - cp_cardinal_rc1a
      - cp_granary_pro_rc8
      - cp_kalinka_rc5
      - cp_prolands_b3b
      - cp_obscure_final
      - cp_reckoner_rc4a
      - cp_warmfrost_rc1
      - cp_warmfront
      - cp_propaganda_b15
      - koth_ashville_rc1
      - koth_bagel_rc2a
      - koth_cascade_rc1a
      - koth_clearcut_b15c
      - koth_coalplant_b8
      - koth_product_rcx
      - koth_ramjam_rc1
      - koth_sandstone_pro_rc1
      - koth_trainsawlaser_rc2
      - mge_oihguv_sucks_a12
      - mge_bball_v2
      - mge_chillypunch_final3
      - mge_training_v8_beta4b
      - pl_badwater_pro_v12
      - pl_barnblitz_pro6
      - ultiduo_baloo
      - ultiduo_gullywash_b2
      - ultiduo_lookout_a7

    - name: Remove unneeded maps
      file:
        path: "{{ srcds_root_dir }}/tf2/tf/maps/{{ item }}.bsp"
        state: absent
      with_items:
        - arena_badlands
        - arena_byre
        - arena_granary
        - arena_lumberyard
        - arena_nucleus
        - arena_offblast_final
        - arena_ravine
        - arena_sawmill
        - arena_watchtower
        - arena_well
        - background01
        - cp_5gorge
        - cp_cloak
        - cp_degrootkeep
        - cp_dustbowl
        - cp_egypt_final
        - cp_fastlane
        - cp_gorge
        - cp_gorge_event
        - cp_granary
        - cp_junction_final
        - cp_manor_event
        - cp_mercenarypark
        - cp_mossrock
        - cp_mountainlab
        - cp_powerhouse
        - cp_snowplow
        - cp_standin_final
        - cp_sunshine_event
        - cp_well
        - ctf_2fort
        - ctf_2fort_invasion
        - ctf_doublecross
        - ctf_foundry
        - ctf_gorge
        - ctf_hellfire
        - ctf_landfall
        - ctf_sawmill
        - ctf_snowfall_final
        - ctf_thundermountain
        - itemtest
        - koth_badlands
        - koth_bagel_event
        - koth_brazil
        - koth_harvest_event
        - koth_harvest_final
        - koth_highpass
        - koth_king
        - koth_lakeside_event
        - koth_lazarus
        - koth_megalo
        - koth_maple_ridge_event
        - koth_moonshine_event
        - koth_nucleus
        - koth_probed
        - koth_sawmill
        - koth_slasher
        - koth_slaughter_event
        - koth_suijin
        - koth_undergrove_event
        - koth_viaduct
        - koth_viaduct_event
        - mvm_bigrock
        - mvm_coaltown
        - mvm_decoy
        - mvm_ghost_town
        - mvm_mannhattan
        - mvm_mannworks
        - mvm_rottenburg
        - pass_brickyard
        - pass_district
        - pass_timbertown
        - pd_cursed_cove_event
        - pd_monster_bash
        - pd_pit_of_death_event
        - pd_snowville_event
        - pd_watergate
        - pl_badwater
        - pl_bloodwater
        - pl_barnblitz
        - pl_cactuscanyon
        - pl_enclosure_final
        - pl_fifthcurve_event
        - pl_frontier_final
        - pl_hasslecastle
        - pl_goldrush
        - pl_hoodoo_final
        - pl_millstone_event
        - pl_precipice_event_final
        - pl_rumble_event
        - pl_snowycoast
        - pl_thundermountain
        - pl_wutville_event
        - plr_bananabay
        - plr_hightower
        - plr_hightower_event
        - plr_nightfall_final
        - plr_pipeline
        - rd_asteroid
        - sd_doomsday
        - sd_doomsday_event
        - tc_hydro
        - tr_dustbowl
        - tr_target

    - name: Install Sourcemod
      include_role:
        name: sourcemod

    - name: Install SourcePython
      include_role:
        name: sourcepython

    - name: Install SourceMod Plugins
      include_role:
        name: "{{ item }}"
      with_items:
        - sm-curl
        - sm-mge
        - sm-soapdm
        - sm-comp
        - sm-demostf
        - sm-meleeonly

    - name: Install SourcePython Plugins
      include_role:
        name: "{{ item }}"
      with_items:
        - sp-logger
        - sp-reservation
        - sp-gamemodes
        - sp-admin
        - sp-connect
        - sp-match
        - sp-logstfdiscord

    - name: Install mapcycle
      template:
        src: templates/mapcycle.txt
        dest: "{{ srcds_root_dir }}/tf2/tf/cfg/mapcycle.txt"
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
        mode: 0644

    - name: Install Server config
      template:
        src: templates/competitive.cfg.j2
        dest: "{{ srcds_root_dir }}/tf2/tf/cfg/server.cfg"
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
        mode: 0600

    - name: Disable Unneeded Soucemod Plugins
      command: "{{ item }}"
      with_items:
        - mv "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/funcommands.smx" "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/disabled/"
        - mv "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/basevotes.smx" "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/disabled/"
        - mv "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/nextmap.smx" "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/disabled/"
        #- mv "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/logstf.smx" "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/disabled/"
        #- mv "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/demostf.smx" "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/disabled/"
        #- mv "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/recordstv.smx" "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/disabled/"

    - name: Add startup and shutdown scripts
      copy:
        src: "files/{{ item }}"
        dest: "{{ item }}"
        owner: "root"
        group: "root"
        mode: 0700
      with_items:
        - /opt/startup.py
        - /opt/cron_shutdown.py
        - /opt/cron_load_auth.py

    - name: Install cron_shutdown deps
      pip:
        executable: pip3
        name:
          - requests
          - boto3

    - name: Cronjob for checking shutdown
      cron:
        name: cron_shutdown
        minute: "*"
        job: "/usr/bin/python3.6 /opt/cron_shutdown.py >> /var/log/cron_shutdown.log 2>&1"

    - name: Cronjob for refreshing auth
      cron:
        name: cron_load_auth
        minute: "*"
        job: "/usr/bin/python3.6 /opt/cron_load_auth.py >> /var/log/cron_load_auth.log 2>&1"

    - name: Create symlink for tf2
      file:
        src: "{{ srcds_root_dir }}/tf2/tf/"
        dest: "/tf2"
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
        state: link

    - name: Add system aliases
      lineinfile:
        path: /etc/bash.bashrc
        line: "{{ item }}"
        create: yes
      with_items:
        - 'alias srcds="/usr/bin/tmux -S /usr/games/steam/tf2/tmux.sock attach"'
        - 'alias tags="jq -S . /opt/tags.json"'
        - 'alias connect="echo \"connect $(curl --silent 169.254.169.254/latest/meta-data/public-ipv4); password $(cat /opt/tags.json | jq .server_password)\""'

    - name: Creates sp auth directory
      file:
        path: "{{ srcds_root_dir }}/tf2/tf/cfg/source-python/auth/"
        state: directory
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
        recurse: yes

    - name: Install sp auth configs
      copy:
        src: "files/auth/{{ item }}"
        dest: "{{ srcds_root_dir }}/tf2/tf/cfg/source-python/auth/{{ item }}"
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
      with_items:
        - parents.json

    - name: Telegraf srcds config
      copy:
        src: files/etc/telegraf/telegraf.d/srcds.conf
        dest: /etc/telegraf/telegraf.d/srcds.conf
        owner: telegraf
        group: telegraf
        mode: 0600

    - name: Telegraf srcds config
      copy:
        src: files/etc/telegraf/telegraf.d/srcds.sh
        dest: /etc/telegraf/telegraf.d/srcds.sh
        owner: telegraf
        group: telegraf
        mode: 0600

    - name: Telegraf connect config
      copy:
        src: files/etc/telegraf/telegraf.d/connect_log.conf
        dest: /etc/telegraf/telegraf.d/connect_log.conf
        owner: telegraf
        group: telegraf
        mode: 0600
