---
- hosts: localhost
  become: true
  connection: local
  gather_facts: no
    
  vars:
    srcds_root_dir: /usr/games/steam/
    srcds_user: steam
  
  roles:
    - role: utils
    - role: security
    - role: monitoring
    - role: srcds
      http_root: "{{ srcds_root_dir }}/tf2/tf/custom/mapdl/"
    
  tasks:
    - name: Create custom map folder
      file:
        path: "{{ srcds_root_dir }}/tf2/tf/custom/mapdl/maps/"
        state: directory
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"

    - name: Download custom maps
      get_url:
        url: "http://maps.tf2.games/maps/{{ item }}.bsp"
        dest: "{{ srcds_root_dir }}/tf2/tf/custom/mapdl/maps/{{ item }}.bsp"
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
        mode: 0444
      ignore_errors: yes
      with_items:
      - cp_cardinal_rc1a
      - cp_granary_pro_rc8
      - cp_kalinka_rc5
      - cp_prolands_b3b
      - cp_obscure_final
      - cp_reckoner_rc4a
      - cp_warmfrost_rc1
      - cp_warmfront
      - cp_propaganda_b14    
      - koth_ashville_rc1
      - koth_bagel_rc2a
      - koth_cascade_rc1a
      - koth_coalplant_b8
      - koth_product_rcx
      - koth_ramjam_rc1
      - koth_sandstone_pro_rc1
      - koth_trainsawlaser_rc2
      - mge_oihguv_sucks_a12
      - mge_bball_v2
      - mge_chillypunch_final3
      - mge_training_v8_beta4b
      - pl_badwater_pro_v12
      - pl_barnblitz_pro6
      - ultiduo_baloo
      - ultiduo_gullywash_b2
      - ultiduo_lookout_a7
  
    - name: Install Sourcemod
      include_role:
        name: sourcemod
        
    - name: Install SourcePython
      include_role:
        name: sourcepython
        
    - name: Install SourceMod Plugins
      include_role: 
        name: "{{ item }}"
      with_items:
        - sm-curl
        - sm-mge
        - sm-soapdm
        - sm-comp
        - sm-demostf
        - sm-meleeonly

    - name: Install SourcePython Plugins
      include_role: 
        name: "{{ item }}"
      with_items:
        - sp-logger
        - sp-reservation
        - sp-gamemodes
        - sp-admin
        - sp-connect
        
    - name: Install Server config
      template:
        src: templates/competitive.cfg.j2
        dest: "{{ srcds_root_dir }}/tf2/tf/cfg/server.cfg"
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
        mode: 0600   
        
    - name: Disable Unneeded Soucemod Plugins
      command: "{{ item }}" 
      with_items: 
        - mv "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/funcommands.smx" "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/disabled/" 
        - mv "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/basevotes.smx" "{{ srcds_root_dir }}/tf2/tf/addons/sourcemod/plugins/disabled/" 

    - name: Upload startup script
      template:
        src: files/opt/startup.sh
        dest: "/opt/startup.sh"
        owner: "root"
        group: "root"
        mode: 0700                  

    - name: Upload shutdown script
      template:
        src: files/opt/shutdown.sh
        dest: "/opt/shutdown.sh"
        owner: "root"
        group: "root"
        mode: 0700  

    - name: Upload cron_shutdown script
      template:
        src: files/opt/cron_shutdown.py
        dest: "/opt/cron_shutdown.py"
        owner: "root"
        group: "root"
        mode: 0700    

    - name: Telegraf srcds config
      copy:
        src: files/etc/telegraf/telegraf.d/srcds.conf
        dest: /etc/telegraf/telegraf.d/srcds.conf
        owner: telegraf
        group: telegraf
        mode: 0700

    - name: Telegraf srcds config
      copy:
        src: files/etc/telegraf/telegraf.d/srcds.sh
        dest: /etc/telegraf/telegraf.d/srcds.sh
        owner: telegraf
        group: telegraf
        mode: 0600

    - name: Cronjob for checking shutdown
      cron:
        minute: "*"
        job: "/usr/bin/python3.6 /opt/cron_shutdown.py"      

    - name: Create symlink for tf2
      file:
        src: "{{ srcds_root_dir }}/tf2/tf/"
        dest: "/tf2"
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
        state: link
    
    - name: Add system aliases
      lineinfile:
        path: /etc/bash.bashrc
        line: "{{ item }}"
        create: yes
      with_items:
        - 'alias srcds="/usr/bin/tmux -S /usr/games/steam/tf2/tmux.sock attach"'

    - name: Creates sp auth directory
      file:
        path: "{{ srcds_root_dir }}/tf2/tf/cfg/source-python/auth/"
        state: directory
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
        recurse: yes

    - name: Install sp auth configs
      copy:
        src: "files/auth/{{ item }}"
        dest: "{{ srcds_root_dir }}/tf2/tf/cfg/source-python/auth/{{ item }}"
        owner: "{{ srcds_user }}"
        group: "{{ srcds_user }}"
      with_items:
        - players.json
        - parents.json
        - simple.txt