---
- name: Create Logger Plugin directories
  file:
    path: "{{ srcds_root_dir }}/tf2/tf/{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - addons/source-python/plugins/logger/

- name: Install Logger Plugin
  copy:
    src: files/addons/source-python/plugins/logger/logger.py
    dest: "{{ srcds_root_dir }}/tf2/tf/addons/source-python/plugins/logger/logger.py"
    owner: steam
    group: steam

