---
- hosts: localhost
  become: true
  connection: local
  gather_facts: no

  roles:
    - role: utils
    - role: security
    - role: monitoring

  tasks:
    - name: Install prereq's
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - adduser
        - libfontconfig1

    - name: Install Grafana server
      apt:
        deb: https://dl.grafana.com/oss/release/grafana_6.3.3_amd64.deb

    - name: Enable Grafana service
      service:
         name: grafana-server
         enabled: yes

    - name: Install Nginx
      apt:
        name: "nginx"
        state: latest

    - name: Install Nginx Grafana site
      apt:
        name: "nginx"
        state: latest

    - name: Create Nginx user
      user:
        name: nginx
        state: present

    - name: Install Nginx
      apt:
        name: "nginx"
        state: latest

    - name: Copy Grafana Nginx config
      template:
        src: files/etc/nginx/sites-available/grafana.conf
        dest: /etc/nginx/sites-available/grafana.conf
        owner: nginx
        group: nginx
        mode: 0644

    - name: Enable Grafana Nginx config
      file:
        src: /etc/nginx/sites-available/grafana.conf
        dest: /etc/nginx/sites-enabled/grafana.conf
        owner: nginx
        group: nginx
        state: link

    - name: Remove Nginx default site
      ignore_errors: yes
      command: rm /etc/nginx/sites-enabled/default
